name: Feature Request
description: Suggest a new feature for IronCompress
title: "[Feature]: "
labels: ["enhancement", "new feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the details below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the feature you'd like.
      placeholder: I would like IronCompress to support...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve or the use case it enables.
      placeholder: This would be useful when...
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project does this feature affect?
      options:
        - Rust (compression algorithms)
        - Java API
        - FFM / FFI layer
        - Benchmarks
        - CI / Build
        - Documentation
      default: 0
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have an idea of how this could be implemented, describe it here.
      placeholder: A possible approach would be...
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
    validations:
      required: false
